AWSTemplateFormatVersion: 2010-09-09
Description: Create a RDS Database instance for GO Shop

Metadata:
 AWS::CloudFormation::Interface:
  ParameterGroups:
   -
    Label:
     default: Database parameters
    Parameters:
     - sevendaysDatabaseInstanceIdentifier
     - sevendaysDatabaseName
     - sevendaysDatabaseUser
     - sevendaysDatabasePassword
     - sevendaysDatabaseBackupRetentionPeriod
     - sevendaysDatabaseAllocatedStorage
     - sevendaysDatabaseInstanceClass
     - sevendaysMultiAZDatabase

Parameters:
 sevendaysDatabaseInstanceIdentifier:
  AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*' #only numbers and letters allowed in parameters name
  ConstraintDescription: RDS Database identifier can only have numbers and letters in its name
  Default: sevendaysRDS
  Description: Database instance identifier name
  MaxLength: 60
  MinLength: 1
  Type: String
  
 sevendaysDatabaseName:
  AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*' #only numbers and letters allowed in parameters name
  ConstraintDescription: RDS Database name can only have numbers and letters in its name
  Default: sevendaysRDS
  Description: Database name
  MaxLength: 64
  MinLength: 1
  Type: String
  
 sevendaysDatabaseUser:
  AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*' #only numbers and letters allowed in parameters name
  ConstraintDescription: RDS Database username can only have numbers and letters in its name
  Default: admin
  Description: Database username
  MaxLength: 16
  MinLength: 1
  NoEcho: false
  Type: String
  
 sevendaysDatabasePassword:
  AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*' #only numbers and letters allowed in parameters name
  ConstraintDescription: RDS Database password can only have numbers and letters in its name
  Default: Password01
  Description: Database password
  MaxLength: 41
  MinLength: 8
  NoEcho: true
  Type: String
  
 sevendaysDatabaseBackupRetentionPeriod:
  ConstraintDescription: RDS Database maximum backup retention period
  Default: 7
  Description: Number of days to retain database backup snapshots
  MaxValue: 35
  MinValue: 0
  NoEcho: false
  Type: Number
 
 sevendaysDatabaseAllocatedStorage:
  ConstraintDescription: Sizae must be between 5 and 1024GB
  Default: 200
  Description: Database size
  MaxValue: 65536
  MinValue: 5
  NoEcho: false
  Type: Number
  
 sevendaysDatabaseInstanceClass:
  AllowedValues:
   - db.t1.micro
   - db.t2.micro
   - db.m1.small
   - db.m1.medium
   - db.m1.large
  ConstraintDescription: Must be a valid database instance type
  Default: db.t2.micro # Smallest possible RDS instance Type
  Description: Database instance type
  Type: String
  
 sevendaysMultiAZDatabase:
  AllowedValues:
   - true
   - false
  ConstraintDescription: true or false
  Default: false # Muti-AZ database not required
  Description: Muti-AZ Database
  Type: String
  
Resources:
 sevendaysDatabaseSubnetGroup:
  Type: AWS::RDS::DBSubnetGroup
  Properties:
   DBSubnetGroupDescription: Subnet group for RDS Database
   SubnetIds:
    - subnet-0a875feaf63912eb3
    - subnet-068343ae900c23b5f
   Tags:
    - Key: name
      Value: sevendaysDBSubnetGroup
 
 sevendaysDatabaseInstance:
  Type: AWS::RDS::DBInstance
  Properties:
   AllocatedStorage: !Ref sevendaysDatabaseAllocatedStorage
   AvailabilityZone: !Select [ 0, !GetAZs '']
   BackupRetentionPeriod: !Ref sevendaysDatabaseBackupRetentionPeriod
   DBInstanceClass: !Ref sevendaysDatabaseInstanceClass
   DBInstanceIdentifier: !Ref sevendaysDatabaseInstanceIdentifier
   DBName: sevendaysDatabaseName
   DBSubnetGroupName: !Ref sevendaysDatabaseSubnetGroup
   Engine: mysql # keep in lower case to avoid permission issues
   EngineVersion: 8.0.36
   MasterUsername: !Ref sevendaysDatabaseUser
   MasterUserPassword: !Ref sevendaysDatabasePassword
   MultiAZ: !Ref sevendaysMultiAZDatabase
   VPCSecurityGroups:
    - sg-07df6460ea6256f26 # Check if security group ID for DB is correct
   Tags:
    - Key: Name
      Value: sevendays-RDSDB
      
Outputs:
 sevendaysRDSEndpoint:
  Description: Endpoint address for RDS DB
  Value: {'Fn::GetAtt': ['sevendaysDatabaseInstance','Endpoint.Address']}
  Export:
   Name:
    'Fn::Sub': '${AWS::StackName}-sevendaysRDSEndpoint'
