AWSTemplateFormatVersion: 2010-09-09
Description: Creates secrets for AWS resources to be deployed

Parameters:
    DefaultPassword:
     Description: Default Password
     Type: String
     Default: Hello@123 #The default for all AWS systems.

Resources:
    SecretPassword:
     Type: AWS::SSM::Parameter
     Properties:
      Name: SecretPassword
      Type: String
      Value: !Ref DefaultPassword #Refers to aforementioned parameter.
      Description: The all knowing and all encompassing password
      
Outputs:
    SecretPassword: #Make sure this mathces resource name specified
     Description: Secret Password
     Value:
        'Fn::GetAtt':
        - SecretPassword
        - Value
     Export:
      Name: {"Fn::Sub": "${AWS::StackName}-secretpassword" }
