AWSTemplateFormatVersion: 2010-09-09
Description: Create a RDS Database instance for GO Shop

 
Resources:
 7daysEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
   InstanceType: t2.micro
   ImageId: ami-0440d3b780d96b29d
   KeyName: vockey
   SubnetId: subnet-09b23d88670f58605
   SecurityGroupIds:
    - sg-0797b809a23de4c46
    - sg-0beda6271f5a81040
   Tags:
    - Key: Name
      Value: 7days-EC2
   UserData:
    Fn::Base64:
     !Sub |
     #!/bin/bash -xe
     sudo su
     sleep 10s
     sudo dnf update -y
     sudo dnf install httpd wget php-fpm php-mysqli php-json php php-devel -y
     sleep 20s
     sudo dnf install -y mariadb-server
     sleep 20s
     cd /var/www/html
     wget https://github.com/jptafe/gorgeous_cupcakes/archive/refs/heads/main.zip
     unzip main.zipcp -r gorgeous_cupcakes-main/* /var/www/html/
     rm -rf gorgeous_cupcakes-main main.zip
     sleep 20s
     sudo systemctl enable httpd
     sudo systemctl start httpd
